---
title: "**DEMOGRAPHIC METHODS**"
author: |
  | Joseph T. Lariscy  
  | University of Memphis, USA
fontsize: 12pt
bibliography: references.bib
output: pdf_document
#output:
#  pdf_document:
#classoption: twocolumn
---

Demography is the study of human populations and how they change in size and composition through fertility, mortality, and migration. Demographic methods are the descriptive and modeling techniques used to measure and understand population size, change, composition, and distribution. Population scientists draw data from censuses, vital statistics systems, administrative records, and social surveys. Demographic models can estimate population processes for nations with incomplete censuses or vital statistics systems, adjust for inaccurate data (such as age misreporting), and forecast population trajectories into the future (Preston et al. 2001). The information produced with demographic methods informs researchers and policymakers about current and future demands for education, employment, housing, healthcare, and retirement funding.

|        Many demographic methods focus on describing a population's age and sex composition, because age and sex are key determinants of population dynamics. Population pyramids are one such demographic tool for depicting a population's age and sex structure. Population pyramids are bar charts in which horizontal bars extend to the left (males) and right (females) from a central age axis and represent the size or proportion in each age group. Younger ages are shown at the bottom of the pyramid with progressively higher age groups moving up the figure. Population pyramids are only pyramid shaped for populations with sustained high fertility. For such populations experiencing rapid growth, each younger cohort is larger than the previous cohort. Among lower-fertility countries like the United States, the population pyramid is shaped like a rectangle or barrel. Figure 1 shows the population pyramid for the United States in 2020.

[Figure 1 about here]

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

|        Demographers also use the age dependency ratio to depict a population's age structure. The dependency ratio divides the number of dependent children (ages 0--14 years) and older adults (ages 65+ years) in the numerator by the number of working age adults (ages 15--65 years) in the denominator. High dependency ratios indicate large proportions of children and/or older adults relative to the working-age population. Dependency ratios are high in many developed societies due to a large number of older adults relative to workers. This population aging presents challenges for the diminishing number of workers to meet the retirement and healthcare needs of older adults.
|        Rates are the most fundamental demographic measure of population change. Rates are calculated as the count of a vital event within a specific time period (usually one year) divided by population size exposed to the risk of that event. By relating the number of events to the population at risk, rates allow for comparisons across subpopulations, place, and time. Rates are often multiplied by a constant (e.g., 1,000) to provide more interpretable values, especially when examining rare events. The mid-year population is often used as an approximation of the population size. For example, the crude death rate (CDR) is the number of deaths during a specific time period divided by the population size:

$$
CDR = \frac{Number\;of\;deaths}{Population\;size}\times1,000.  
$$

CDR is considered *crude* because it is sensitive to a population's age structure. If CDRs were compared between two populations, and population A has an older age structure than population B, then the CDR in population A will likely be higher regardless of the health status of each population. For this reason, demographic rates are often presented as age-specific rates.

|        Life tables are one of the most important demographic methods for the study of mortality. Life tables use age-specific death rates to calculate life expectancy at birth and other age-related functions pertaining to mortality, such as number of survivors and deaths at each age and expected years of life remaining beyond ages other than birth [@preston2001]. Life expectancy is a popular summary indicator for describing the longevity of a population. The life expectancy at birth of the United States in 2020 was 76.4 years [@arias2022]. This value does not describe the longevity prospects of an actual birth cohort. Instead, period life tables describe the mortality prospects for a hypothetical cohort (also called a synthetic cohort) if individuals progressed through each age experiencing the age-specific mortality rates of a particular year. A cohort life table could only be constructed after most members of the cohort had died. In contrast, period life tables use death rates for each age in one year to present a current description of a population's longevity.
|        Demographic methods for studying fertility also rely on rates. The crude birth rate (CBR), like the CDR, is the number of the event of interest (in this case, births), divided by the population size. The population in the denominator are not truly *at risk* of having a birth; it includes men as well as women who are too young or old to have a child. Therefore, fertility rates limit the denominator to women of childbearing ages (i.e., 15--49 years). Age-specific fertility rates are used to calculate the total fertility rate (TFR), which describes the average number of children women would have if they experienced the rates of a particular year throughout their reproductive ages. The TFR in 2020 ranged from a high of 6.9 children per woman in Niger to a low of 0.9 in South Korea [@UNpopdiv]. A TFR of 2.1 is considered *replacement level fertility* since this number of births would replace the mother and father, with an allowance for individuals who do not survive through adulthood. Reproduction rates further refine the measurement of fertility by only including female children in the numerator a`nd considering mortality risk of mothers to show whether a generation of women reproduce themselves or produce a surplus of female births (suggesting population growth) or deficit (suggesting population stability or decline).
|        TFR resembles life expectancy in two keys ways. First, life expectancy and TFR translate an aggregate measure into an indicator that is relatable to an individual's life events. Second, both indicators are period measures that describe a hypothetical cohort, rather than an actual birth cohort, to provide a timely description of how a population experiences a demographic phenomenon.

SEE ALSO: Childbearing, International Practices; Gender and Life Expectancy; Migration; Socioeconomic Status and Mortality

**REFERENCES**
